insert into comuna (id,nombre) values ('7203','pelluhue');
insert into comuna (id,nombre) values ('8202','arauco');
insert into comuna (id,nombre) values ('15101','arica');
insert into comuna (id,nombre) values ('8402','bulnes');
insert into comuna (id,nombre) values ('7201','cauquenes');
insert into comuna (id,nombre) values ('11202','cisnes');
insert into comuna (id,nombre) values ('10103','cochamo');
insert into comuna (id,nombre) values ('11301','cochrane');
insert into comuna (id,nombre) values ('9118','tolten');
insert into comuna (id,nombre) values ('11303','tortel');
insert into comuna (id,nombre) values ('7408','yerbas buenas');
insert into comuna (id,nombre) values ('2301','tocopilla');
insert into comuna (id,nombre) values ('2202','ollague');
insert into comuna (id,nombre) values ('8111','tome');
insert into comuna (id,nombre) values ('3202','diego de almagro');
insert into comuna (id,nombre) values ('8403','cobquecura');
insert into comuna (id,nombre) values ('13602','el monte');
insert into comuna (id,nombre) values ('8404','coelemu');
insert into comuna (id,nombre) values ('8405','coihueco');
insert into comuna (id,nombre) values ('14101','valdivia');
insert into comuna (id,nombre) values ('1403','colchane');
insert into comuna (id,nombre) values ('9102','carahue');
insert into comuna (id,nombre) values ('7303','licanten');
insert into comuna (id,nombre) values ('5505','limache');
insert into comuna (id,nombre) values ('5603','cartagena');
insert into comuna (id,nombre) values ('8304','laja');
insert into comuna (id,nombre) values ('10301','osorno');
insert into comuna (id,nombre) values ('4301','ovalle');
insert into comuna (id,nombre) values ('14104','los lagos');
insert into comuna (id,nombre) values ('5106','quilpue');
insert into comuna (id,nombre) values ('8413','quillon');
insert into comuna (id,nombre) values ('8414','quirihue');
insert into comuna (id,nombre) values ('5107','quintero');
insert into comuna (id,nombre) values ('10106','los muermos');
insert into comuna (id,nombre) values ('12201','cabo de hornos');
insert into comuna (id,nombre) values ('12102','laguna blanca');
insert into comuna (id,nombre) values ('9206','los sauces');
insert into comuna (id,nombre) values ('10102','calbuco');
insert into comuna (id,nombre) values ('3102','caldera');
insert into comuna (id,nombre) values ('8415','ranquil');
insert into comuna (id,nombre) values ('7305','rauco');
insert into comuna (id,nombre) values ('9209','renaico');
insert into comuna (id,nombre) values ('13107','huechuraba');
insert into comuna (id,nombre) values ('5201','isla de pascua');
insert into comuna (id,nombre) values ('5104','juan fernandez');
insert into comuna (id,nombre) values ('11302','ohiggins');
insert into comuna (id,nombre) values ('3302','alto del carmen');
insert into comuna (id,nombre) values ('10404','palena');
insert into comuna (id,nombre) values ('11402','rio ibanez');
insert into comuna (id,nombre) values ('12103','rio verde');
insert into comuna (id,nombre) values ('5402','cabildo');
insert into comuna (id,nombre) values ('10202','ancud');
insert into comuna (id,nombre) values ('2101','antofagasta');
insert into comuna (id,nombre) values ('6104','coltauco');
insert into comuna (id,nombre) values ('10305','rio negro');
insert into comuna (id,nombre) values ('8303','cabrero');
insert into comuna (id,nombre) values ('2201','calama');
insert into comuna (id,nombre) values ('13502','alhue');
insert into comuna (id,nombre) values ('8314','alto biobio');
insert into comuna (id,nombre) values ('10201','castro');
insert into comuna (id,nombre) values ('10204','curaco de velez');
insert into comuna (id,nombre) values ('1101','iquique');
insert into comuna (id,nombre) values ('8417','san fabian');
insert into comuna (id,nombre) values ('15202','general lagos');
insert into comuna (id,nombre) values ('11203','guaitecas');
insert into comuna (id,nombre) values ('13120','nunoa');
insert into comuna (id,nombre) values ('6102','codegua');
insert into comuna (id,nombre) values ('8419','san nicolas');
insert into comuna (id,nombre) values ('5507','olmue');
insert into comuna (id,nombre) values ('8406','chillan viejo');
insert into comuna (id,nombre) values ('7102','constitucion');
insert into comuna (id,nombre) values ('13505','san pedro');
insert into comuna (id,nombre) values ('12301','porvenir');
insert into comuna (id,nombre) values ('6106','graneros');
insert into comuna (id,nombre) values ('13122','penalolen');
insert into comuna (id,nombre) values ('10307','san pablo');
insert into comuna (id,nombre) values ('10209','quemchi');
insert into comuna (id,nombre) values ('10105','frutillar');
insert into comuna (id,nombre) values ('10208','quellon');
insert into comuna (id,nombre) values ('10101','puerto montt');
insert into comuna (id,nombre) values ('4103','andacollo');
insert into comuna (id,nombre) values ('9115','pucon');
insert into comuna (id,nombre) values ('9201','angol');
insert into comuna (id,nombre) values ('2203','san pedro de atacama');
insert into comuna (id,nombre) values ('6306','palmilla');
insert into comuna (id,nombre) values ('7202','chanco');
insert into comuna (id,nombre) values ('8302','antuco');
insert into comuna (id,nombre) values ('5108','villa alemana');
insert into comuna (id,nombre) values ('5102','casablanca');
insert into comuna (id,nombre) values ('15102','camarones');
insert into comuna (id,nombre) values ('5302','calle larga');
insert into comuna (id,nombre) values ('6204','marchigue');
insert into comuna (id,nombre) values ('6302','chepica');
insert into comuna (id,nombre) values ('4202','canela');
insert into comuna (id,nombre) values ('5403','papudo');
insert into comuna (id,nombre) values ('12303','timaukel');
insert into comuna (id,nombre) values ('13401','san bernardo');
insert into comuna (id,nombre) values ('8203','canete');
insert into comuna (id,nombre) values ('3303','freirina');
insert into comuna (id,nombre) values ('12402','torres del paine');
insert into comuna (id,nombre) values ('7109','san clemente');
insert into comuna (id,nombre) values ('8407','el carmen');
insert into comuna (id,nombre) values ('9210','traiguen');
insert into comuna (id,nombre) values ('6202','la estrella');
insert into comuna (id,nombre) values ('8206','los alamos');
insert into comuna (id,nombre) values ('5301','los andes');
insert into comuna (id,nombre) values ('8420','treguaco');
insert into comuna (id,nombre) values ('8301','los angeles');
insert into comuna (id,nombre) values ('8310','san rosendo');
insert into comuna (id,nombre) values ('8312','tucapel');
insert into comuna (id,nombre) values ('5101','valparaiso');
insert into comuna (id,nombre) values ('3301','vallenar');
insert into comuna (id,nombre) values ('6304','lolol');
insert into comuna (id,nombre) values ('9109','loncoche');
insert into comuna (id,nombre) values ('8412','portezuelo');
insert into comuna (id,nombre) values ('7403','longavi');
insert into comuna (id,nombre) values ('5706','santa maria');
insert into comuna (id,nombre) values ('9205','lonquimay');
insert into comuna (id,nombre) values ('7106','pelarco');
insert into comuna (id,nombre) values ('13111','la granja');
insert into comuna (id,nombre) values ('7302','hualane');
insert into comuna (id,nombre) values ('7407','villa alegre');
insert into comuna (id,nombre) values ('8105','hualqui');
insert into comuna (id,nombre) values ('9106','galvarino');
insert into comuna (id,nombre) values ('1404','huara');
insert into comuna (id,nombre) values ('13102','cerrillos');
insert into comuna (id,nombre) values ('6111','olivar');
insert into comuna (id,nombre) values ('3304','huasco');
insert into comuna (id,nombre) values ('13124','pudahuel');
insert into comuna (id,nombre) values ('9112','padre las casas');
insert into comuna (id,nombre) values ('8309','quilleco');
insert into comuna (id,nombre) values ('8108','san pedro de la paz');
insert into comuna (id,nombre) values ('5501','quillota');
insert into comuna (id,nombre) values ('5704','panquehue');
insert into comuna (id,nombre) values ('10210','quinchao');
insert into comuna (id,nombre) values ('9107','gorbea');
insert into comuna (id,nombre) values ('8313','yumbel');
insert into comuna (id,nombre) values ('8421','yungay');
insert into comuna (id,nombre) values ('13301','colina');
insert into comuna (id,nombre) values ('10403','hualaihue');
insert into comuna (id,nombre) values ('7103','curepto');
insert into comuna (id,nombre) values ('14102','corral');
insert into comuna (id,nombre) values ('11101','coyhaique');
insert into comuna (id,nombre) values ('6303','chimbarongo');
insert into comuna (id,nombre) values ('9121','cholchol');
insert into comuna (id,nombre) values ('5405','zapallar');
insert into comuna (id,nombre) values ('11102','lago verde');
insert into comuna (id,nombre) values ('8201','lebu');
insert into comuna (id,nombre) values ('8408','ninhue');
insert into comuna (id,nombre) values ('13303','tiltil');
insert into comuna (id,nombre) values ('5401','la ligua');
insert into comuna (id,nombre) values ('8418','san ignacio');
insert into comuna (id,nombre) values ('7110','san rafael');
insert into comuna (id,nombre) values ('6201','pichilemu');
insert into comuna (id,nombre) values ('9114','pitrufquen');
insert into comuna (id,nombre) values ('12401','natales');
insert into comuna (id,nombre) values ('5303','rinconada');
insert into comuna (id,nombre) values ('8416','san carlos');
insert into comuna (id,nombre) values ('13501','melipilla');
insert into comuna (id,nombre) values ('8102','coronel');
insert into comuna (id,nombre) values ('2104','taltal');
insert into comuna (id,nombre) values ('3103','tierra amarilla');
insert into comuna (id,nombre) values ('10108','maullin');
insert into comuna (id,nombre) values ('8311','santa barbara');
insert into comuna (id,nombre) values ('3201','chanaral');
insert into comuna (id,nombre) values ('7105','maule');
insert into comuna (id,nombre) values ('10401','chaiten');
insert into comuna (id,nombre) values ('10402','futaleufu');
insert into comuna (id,nombre) values ('13201','puente alto');
insert into comuna (id,nombre) values ('5304','san esteban');
insert into comuna (id,nombre) values ('13131','san ramon');
insert into comuna (id,nombre) values ('5701','san felipe');
insert into comuna (id,nombre) values ('4201','illapel');
insert into comuna (id,nombre) values ('7307','sagrada familia');
insert into comuna (id,nombre) values ('7406','san javier');
insert into comuna (id,nombre) values ('13103','cerro navia');
insert into comuna (id,nombre) values ('13601','talagante');
insert into comuna (id,nombre) values ('1401','pozo almonte');
insert into comuna (id,nombre) values ('13404','paine');
insert into comuna (id,nombre) values ('12302','primavera');
insert into comuna (id,nombre) values ('13402','buin');
insert into comuna (id,nombre) values ('7401','linares');
insert into comuna (id,nombre) values ('6305','nancagua');
insert into comuna (id,nombre) values ('15201','putre');
insert into comuna (id,nombre) values ('13121','pedro aguirre cerda');
insert into comuna (id,nombre) values ('10304','puyehue');
insert into comuna (id,nombre) values ('13129','san joaquin');
insert into comuna (id,nombre) values ('10207','queilen');
insert into comuna (id,nombre) values ('6206','paredones');
insert into comuna (id,nombre) values ('13126','quinta normal');
insert into comuna (id,nombre) values ('9108','lautaro');
insert into comuna (id,nombre) values ('13503','curacavi');
insert into comuna (id,nombre) values ('13127','recoleta');
insert into comuna (id,nombre) values ('8308','quilaco');
insert into comuna (id,nombre) values ('4101','la serena');
insert into comuna (id,nombre) values ('14201','la union');
insert into comuna (id,nombre) values ('1402','camina');
insert into comuna (id,nombre) values ('14203','lago ranco');
insert into comuna (id,nombre) values ('10302','puerto octay');
insert into comuna (id,nombre) values ('6115','rengo');
insert into comuna (id,nombre) values ('6105','donihue');
insert into comuna (id,nombre) values ('6116','requinoa');
insert into comuna (id,nombre) values ('6108','machali');
insert into comuna (id,nombre) values ('14105','mafil');
insert into comuna (id,nombre) values ('6109','malloa');
insert into comuna (id,nombre) values ('13504','maria pinto');
insert into comuna (id,nombre) values ('2302','maria elena');
insert into comuna (id,nombre) values ('14106','mariquina');
insert into comuna (id,nombre) values ('1405','pica');
insert into comuna (id,nombre) values ('6203','litueche');
insert into comuna (id,nombre) values ('13115','lo barnechea');
insert into comuna (id,nombre) values ('13132','vitacura');
insert into comuna (id,nombre) values ('6110','mostazal');
insert into comuna (id,nombre) values ('8410','pemuco');
insert into comuna (id,nombre) values ('5105','puchuncavi');
insert into comuna (id,nombre) values ('13109','la cisterna');
insert into comuna (id,nombre) values ('14108','panguipulli');
insert into comuna (id,nombre) values ('7405','retiro');
insert into comuna (id,nombre) values ('8307','negrete');
insert into comuna (id,nombre) values ('2102','mejillones');
insert into comuna (id,nombre) values ('8207','tirua');
insert into comuna (id,nombre) values ('6310','santa cruz');
insert into comuna (id,nombre) values ('8109','santa juana');
insert into comuna (id,nombre) values ('7104','empedrado');
insert into comuna (id,nombre) values ('8104','florida');
insert into comuna (id,nombre) values ('9204','ercilla');
insert into comuna (id,nombre) values ('9105','freire');
insert into comuna (id,nombre) values ('6301','san fernando');
insert into comuna (id,nombre) values ('12104','san gregorio');
insert into comuna (id,nombre) values ('10306','san juan de la costa');
insert into comuna (id,nombre) values ('10206','puqueldon');
insert into comuna (id,nombre) values ('2103','sierra gorda');
insert into comuna (id,nombre) values ('11401','chile chico');
insert into comuna (id,nombre) values ('10203','chonchi');
insert into comuna (id,nombre) values ('10205','dalcahue');
insert into comuna (id,nombre) values ('5404','petorca');
insert into comuna (id,nombre) values ('7404','parral');
insert into comuna (id,nombre) values ('5606','santo domingo');
insert into comuna (id,nombre) values ('9202','collipulli');
insert into comuna (id,nombre) values ('4302','combarbala');
insert into comuna (id,nombre) values ('8101','concepcion');
insert into comuna (id,nombre) values ('8204','contulmo');
insert into comuna (id,nombre) values ('3101','copiapo');
insert into comuna (id,nombre) values ('4102','coquimbo');
insert into comuna (id,nombre) values ('9103','cunco');
insert into comuna (id,nombre) values ('9203','curacautin');
insert into comuna (id,nombre) values ('8205','curanilahue');
insert into comuna (id,nombre) values ('6113','pichidegua');
insert into comuna (id,nombre) values ('5604','el quisco');
insert into comuna (id,nombre) values ('9104','curarrehue');
insert into comuna (id,nombre) values ('5601','san antonio');
insert into comuna (id,nombre) values ('5103','concon');
insert into comuna (id,nombre) values ('7301','curico');
insert into comuna (id,nombre) values ('6308','placilla');
insert into comuna (id,nombre) values ('4104','la higuera');
insert into comuna (id,nombre) values ('6103','coinco');
insert into comuna (id,nombre) values ('14103','lanco');
insert into comuna (id,nombre) values ('13604','padre hurtado');
insert into comuna (id,nombre) values ('13108','independencia');
insert into comuna (id,nombre) values ('4106','vicuna');
insert into comuna (id,nombre) values ('7309','vichuquen');
insert into comuna (id,nombre) values ('6112','peumo');
insert into comuna (id,nombre) values ('9211','victoria');
insert into comuna (id,nombre) values ('6101','rancagua');
insert into comuna (id,nombre) values ('9119','vilcun');
insert into comuna (id,nombre) values ('13403','calera de tango');
insert into comuna (id,nombre) values ('13116','lo espejo');
insert into comuna (id,nombre) values ('9110','melipeuco');
insert into comuna (id,nombre) values ('14202','futrono');
insert into comuna (id,nombre) values ('9120','villarrica');
insert into comuna (id,nombre) values ('6107','las cabras');
insert into comuna (id,nombre) values ('5602','algarrobo');
insert into comuna (id,nombre) values ('5502','calera');
insert into comuna (id,nombre) values ('13130','san miguel');
insert into comuna (id,nombre) values ('8411','pinto');
insert into comuna (id,nombre) values ('13603','isla de maipo');
insert into comuna (id,nombre) values ('13202','pirque');
insert into comuna (id,nombre) values ('5702','catemu');
insert into comuna (id,nombre) values ('8103','chiguayante');
insert into comuna (id,nombre) values ('6309','pumanque');
insert into comuna (id,nombre) values ('13114','las condes');
insert into comuna (id,nombre) values ('14107','paillaco');
insert into comuna (id,nombre) values ('10109','puerto varas');
insert into comuna (id,nombre) values ('4304','punitaqui');
insert into comuna (id,nombre) values ('5109','vina del mar');
insert into comuna (id,nombre) values ('12101','punta arenas');
insert into comuna (id,nombre) values ('13119','maipu');
insert into comuna (id,nombre) values ('9208','puren');
insert into comuna (id,nombre) values ('10303','purranque');
insert into comuna (id,nombre) values ('5705','putaendo');
insert into comuna (id,nombre) values ('5504','la cruz');
insert into comuna (id,nombre) values ('4203','los vilos');
insert into comuna (id,nombre) values ('13302','lampa');
insert into comuna (id,nombre) values ('9207','lumaco');
insert into comuna (id,nombre) values ('5605','el tabo');
insert into comuna (id,nombre) values ('13117','lo prado');
insert into comuna (id,nombre) values ('13110','la florida');
insert into comuna (id,nombre) values ('8112','hualpen');
insert into comuna (id,nombre) values ('6114','quinta de tilcoco');
insert into comuna (id,nombre) values ('9113','perquenco');
insert into comuna (id,nombre) values ('5503','hijuelas');
insert into comuna (id,nombre) values ('14204','rio bueno');
insert into comuna (id,nombre) values ('7101','talca');
insert into comuna (id,nombre) values ('7108','rio claro');
insert into comuna (id,nombre) values ('7306','romeral');
insert into comuna (id,nombre) values ('4305','rio hurtado');
insert into comuna (id,nombre) values ('1107','alto hospicio');
insert into comuna (id,nombre) values ('4204','salamanca');
insert into comuna (id,nombre) values ('13104','conchali');
insert into comuna (id,nombre) values ('13105','el bosque');
insert into comuna (id,nombre) values ('13125','quilicura');
insert into comuna (id,nombre) values ('7304','molina');
insert into comuna (id,nombre) values ('4303','monte patria');
insert into comuna (id,nombre) values ('8305','mulchen');
insert into comuna (id,nombre) values ('8306','nacimiento');
insert into comuna (id,nombre) values ('8409','niquen');
insert into comuna (id,nombre) values ('5506','nogales');
insert into comuna (id,nombre) values ('9111','nueva imperial');
insert into comuna (id,nombre) values ('6117','san vicente');
insert into comuna (id,nombre) values ('8106','lota');
insert into comuna (id,nombre) values ('13128','renca');
insert into comuna (id,nombre) values ('8110','talcahuano');
insert into comuna (id,nombre) values ('8401','chillan');
insert into comuna (id,nombre) values ('10107','llanquihue');
insert into comuna (id,nombre) values ('13101','santiago');
insert into comuna (id,nombre) values ('13123','providencia');
insert into comuna (id,nombre) values ('7107','pencahue');
insert into comuna (id,nombre) values ('13112','la pintana');
insert into comuna (id,nombre) values ('8107','penco');
insert into comuna (id,nombre) values ('6307','peralillo');
insert into comuna (id,nombre) values ('13113','la reina');
insert into comuna (id,nombre) values ('9116','saavedra');
insert into comuna (id,nombre) values ('13118','macul');
insert into comuna (id,nombre) values ('10104','fresia');
insert into comuna (id,nombre) values ('7402','colbun');
insert into comuna (id,nombre) values ('13203','san jose de maipo');
insert into comuna (id,nombre) values ('6205','navidad');
insert into comuna (id,nombre) values ('4105','paihuano');
insert into comuna (id,nombre) values ('7308','teno');
insert into comuna (id,nombre) values ('9117','teodoro schmidt');
insert into comuna (id,nombre) values ('9101','temuco');
insert into comuna (id,nombre) values ('13605','penaflor');